const followers = [
  {
    "login": "rodrigo1808",
    "id": 41304633,
    "node_id": "MDQ6VXNlcjQxMzA0NjMz",
    "avatar_url": "https://avatars.githubusercontent.com/u/41304633?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rodrigo1808",
    "html_url": "https://github.com/rodrigo1808",
    "followers_url": "https://api.github.com/users/rodrigo1808/followers",
    "following_url": "https://api.github.com/users/rodrigo1808/following{/other_user}",
    "gists_url": "https://api.github.com/users/rodrigo1808/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rodrigo1808/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rodrigo1808/subscriptions",
    "organizations_url": "https://api.github.com/users/rodrigo1808/orgs",
    "repos_url": "https://api.github.com/users/rodrigo1808/repos",
    "events_url": "https://api.github.com/users/rodrigo1808/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rodrigo1808/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "larissadalimar",
    "id": 41343511,
    "node_id": "MDQ6VXNlcjQxMzQzNTEx",
    "avatar_url": "https://avatars.githubusercontent.com/u/41343511?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/larissadalimar",
    "html_url": "https://github.com/larissadalimar",
    "followers_url": "https://api.github.com/users/larissadalimar/followers",
    "following_url": "https://api.github.com/users/larissadalimar/following{/other_user}",
    "gists_url": "https://api.github.com/users/larissadalimar/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/larissadalimar/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/larissadalimar/subscriptions",
    "organizations_url": "https://api.github.com/users/larissadalimar/orgs",
    "repos_url": "https://api.github.com/users/larissadalimar/repos",
    "events_url": "https://api.github.com/users/larissadalimar/events{/privacy}",
    "received_events_url": "https://api.github.com/users/larissadalimar/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "lagaleno",
    "id": 18380771,
    "node_id": "MDQ6VXNlcjE4MzgwNzcx",
    "avatar_url": "https://avatars.githubusercontent.com/u/18380771?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/lagaleno",
    "html_url": "https://github.com/lagaleno",
    "followers_url": "https://api.github.com/users/lagaleno/followers",
    "following_url": "https://api.github.com/users/lagaleno/following{/other_user}",
    "gists_url": "https://api.github.com/users/lagaleno/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/lagaleno/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/lagaleno/subscriptions",
    "organizations_url": "https://api.github.com/users/lagaleno/orgs",
    "repos_url": "https://api.github.com/users/lagaleno/repos",
    "events_url": "https://api.github.com/users/lagaleno/events{/privacy}",
    "received_events_url": "https://api.github.com/users/lagaleno/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "dandeeccastro",
    "id": 26532284,
    "node_id": "MDQ6VXNlcjI2NTMyMjg0",
    "avatar_url": "https://avatars.githubusercontent.com/u/26532284?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dandeeccastro",
    "html_url": "https://github.com/dandeeccastro",
    "followers_url": "https://api.github.com/users/dandeeccastro/followers",
    "following_url": "https://api.github.com/users/dandeeccastro/following{/other_user}",
    "gists_url": "https://api.github.com/users/dandeeccastro/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dandeeccastro/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dandeeccastro/subscriptions",
    "organizations_url": "https://api.github.com/users/dandeeccastro/orgs",
    "repos_url": "https://api.github.com/users/dandeeccastro/repos",
    "events_url": "https://api.github.com/users/dandeeccastro/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dandeeccastro/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Gaizgrol",
    "id": 28551993,
    "node_id": "MDQ6VXNlcjI4NTUxOTkz",
    "avatar_url": "https://avatars.githubusercontent.com/u/28551993?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Gaizgrol",
    "html_url": "https://github.com/Gaizgrol",
    "followers_url": "https://api.github.com/users/Gaizgrol/followers",
    "following_url": "https://api.github.com/users/Gaizgrol/following{/other_user}",
    "gists_url": "https://api.github.com/users/Gaizgrol/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Gaizgrol/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Gaizgrol/subscriptions",
    "organizations_url": "https://api.github.com/users/Gaizgrol/orgs",
    "repos_url": "https://api.github.com/users/Gaizgrol/repos",
    "events_url": "https://api.github.com/users/Gaizgrol/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Gaizgrol/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "RafaelxFernandes",
    "id": 32852162,
    "node_id": "MDQ6VXNlcjMyODUyMTYy",
    "avatar_url": "https://avatars.githubusercontent.com/u/32852162?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/RafaelxFernandes",
    "html_url": "https://github.com/RafaelxFernandes",
    "followers_url": "https://api.github.com/users/RafaelxFernandes/followers",
    "following_url": "https://api.github.com/users/RafaelxFernandes/following{/other_user}",
    "gists_url": "https://api.github.com/users/RafaelxFernandes/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/RafaelxFernandes/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/RafaelxFernandes/subscriptions",
    "organizations_url": "https://api.github.com/users/RafaelxFernandes/orgs",
    "repos_url": "https://api.github.com/users/RafaelxFernandes/repos",
    "events_url": "https://api.github.com/users/RafaelxFernandes/events{/privacy}",
    "received_events_url": "https://api.github.com/users/RafaelxFernandes/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "ygorflorent",
    "id": 43794443,
    "node_id": "MDQ6VXNlcjQzNzk0NDQz",
    "avatar_url": "https://avatars.githubusercontent.com/u/43794443?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ygorflorent",
    "html_url": "https://github.com/ygorflorent",
    "followers_url": "https://api.github.com/users/ygorflorent/followers",
    "following_url": "https://api.github.com/users/ygorflorent/following{/other_user}",
    "gists_url": "https://api.github.com/users/ygorflorent/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ygorflorent/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ygorflorent/subscriptions",
    "organizations_url": "https://api.github.com/users/ygorflorent/orgs",
    "repos_url": "https://api.github.com/users/ygorflorent/repos",
    "events_url": "https://api.github.com/users/ygorflorent/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ygorflorent/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Tefmath",
    "id": 60139364,
    "node_id": "MDQ6VXNlcjYwMTM5MzY0",
    "avatar_url": "https://avatars.githubusercontent.com/u/60139364?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Tefmath",
    "html_url": "https://github.com/Tefmath",
    "followers_url": "https://api.github.com/users/Tefmath/followers",
    "following_url": "https://api.github.com/users/Tefmath/following{/other_user}",
    "gists_url": "https://api.github.com/users/Tefmath/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Tefmath/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Tefmath/subscriptions",
    "organizations_url": "https://api.github.com/users/Tefmath/orgs",
    "repos_url": "https://api.github.com/users/Tefmath/repos",
    "events_url": "https://api.github.com/users/Tefmath/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Tefmath/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "luismarquezzini",
    "id": 16675397,
    "node_id": "MDQ6VXNlcjE2Njc1Mzk3",
    "avatar_url": "https://avatars.githubusercontent.com/u/16675397?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/luismarquezzini",
    "html_url": "https://github.com/luismarquezzini",
    "followers_url": "https://api.github.com/users/luismarquezzini/followers",
    "following_url": "https://api.github.com/users/luismarquezzini/following{/other_user}",
    "gists_url": "https://api.github.com/users/luismarquezzini/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/luismarquezzini/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/luismarquezzini/subscriptions",
    "organizations_url": "https://api.github.com/users/luismarquezzini/orgs",
    "repos_url": "https://api.github.com/users/luismarquezzini/repos",
    "events_url": "https://api.github.com/users/luismarquezzini/events{/privacy}",
    "received_events_url": "https://api.github.com/users/luismarquezzini/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "mateusmlo",
    "id": 13263031,
    "node_id": "MDQ6VXNlcjEzMjYzMDMx",
    "avatar_url": "https://avatars.githubusercontent.com/u/13263031?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mateusmlo",
    "html_url": "https://github.com/mateusmlo",
    "followers_url": "https://api.github.com/users/mateusmlo/followers",
    "following_url": "https://api.github.com/users/mateusmlo/following{/other_user}",
    "gists_url": "https://api.github.com/users/mateusmlo/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mateusmlo/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mateusmlo/subscriptions",
    "organizations_url": "https://api.github.com/users/mateusmlo/orgs",
    "repos_url": "https://api.github.com/users/mateusmlo/repos",
    "events_url": "https://api.github.com/users/mateusmlo/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mateusmlo/received_events",
    "type": "User",
    "site_admin": false
  }
]

export default followers;
